config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'search', to: 'pages#search'
  resources :assos, only: [:index, :show] do
    resources :missions, only: [:show, :new, :create, :delete, :index]
  end


  resources :users

  resources :missions, only: [:index, :show] do
    resources :favorites, only: [] do
      collection do
        get :toggle_favorite
      end
    end
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :assos, only: [ :index ]
    end
  end

  resources :favorites

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/asso.rb
class Asso < ApplicationRecord
  has_many :missions, dependent: :destroy

  include PgSearch::Model
  pg_search_scope :search_by_all,
    against: [ :name, :description, :category, :city, :zipcode ],
    using: {
      tsearch: { prefix: true }
    }

  scope :geocoded, -> { where.not(latitude: nil, longitude: nil) }

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :mission
  validates :mission, uniqueness: { scope: :mission_id}
end

app/models/mission.rb
class Mission < ApplicationRecord
  belongs_to :asso
  has_many :favorites

    include PgSearch::Model
    pg_search_scope :global_search,
    against: [:title, :lieu],
    associated_against: {
      asso: [:name, :description, :address, :category]
    },
    using: {
      tsearch: { prefix: true }
    }

  def in_favorite?(user)
    self.favorites.find{|favorite| favorite.user_id == user.id}
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :favorites
  has_many :favorites_missions, through: :favorites, source: :mission
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/api/v1/assos_controller.rb
class Api::V1::AssosController < Api::V1::BaseController
  def index
    @assos = Asso.all
  end
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ActionController::API
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/assos_controller.rb
class AssosController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    if params[:query].present?
      # sql_query = "name ILIKE :query OR description ILIKE :query"
      # @assos = Asso.where(sql_query, query: "%#{params[:query]}%")
      @assos = Asso.left_joins(:missions)
      .select('assos.*, COUNT(missions.id) as total_mission')
      .group('assos.id')
      .search_by_all(params[:query])
      .reorder('total_mission DESC')
      .limit(20)
    else
      @assos = Asso.left_joins(:missions)
      .select('assos.*, COUNT(missions.id) as total_mission')
      .group('assos.id')
      .order('total_mission DESC')
      .limit(20)
    end

    @markers = create_map_markers(@assos)
  end

  def show
    @asso = Asso.find(params[:id])
    @marker = [{
        lat: @asso.latitude,
        lng: @asso.longitude,
      }]

     @missions_around_me = Mission.where(asso: @asso)#.where('lieu ILIKE :ville', ville: "%69%")
    #@all_missions = Mission.where(asso: @asso).where.not('lieu ILIKE :ville', ville: "%69%")
  end

  private

  def create_map_markers(assos)
    assos.map do |asso|
      {
        id: asso.id,
        lat: asso.latitude,
        lng: asso.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { asso: asso })
      }
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorites = Favorite.all
  end

  def toggle_favorite
    @mission = Mission.find(params[:mission_id])
    is_favori = Favorite.where(user: current_user, mission: @mission)&.first
    if is_favori
      is_favori.destroy
    else
      Favorite.create(mission: @mission, user: current_user)
    end
    if params[:from] == 'user_favorites'
      redirect_to favorites_path
    elsif params[:from] == 'mission_show'
      redirect_to mission_path(@mission)
    elsif params[:from] == 'asso_show'
      redirect_to asso_path(@mission.asso)
    else
      redirect_to missions_path(query: params[:query])
    end
  end
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    @missions = Mission.all
    if params[:query].present?
      # sql_query = " \
      # missions.title @@ :query \
      # OR missions.lieu @@ :query \
      # OR missions.type_mission @@ :query \
      # OR missions.dispo @@ :query \
      # OR assos.name @@ :query \
      # "
      # @missions = Mission.joins(:asso).where(sql_query, query: "%#{params[:query]}%")
      @missions = Mission.global_search(params[:query]).limit(100)
    else
      @missions = Mission.all.limit(100)
    end
  end


  def show
    @mission = Mission.find(params[:id])
  end

  def new
    @mission = Mission.new
  end

  def create
    @mission = Mission.new(params[:mission])
    @mission.save

    redirect_to mission_path(@mission)
  end

  private

  def mission_params
    params.require(:mission).permit(:name, :address, :description, :longitude, :latitude)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :search]

  def home
    # render layout: 'special'
    @markers = Asso.geocoded.limit(100).map do |asso|
      {
        lat: asso.latitude,
        lng: asso.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { asso: asso })
      }
    end
  end

  def search
    redirect_to send(params[:kind] + '_path', query: params[:query] + " " + params[:category])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    @user.save

    redirect_to user_path(@user)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(params[:user])
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :address, :city, :postal_code, :phone_number)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assos_helper.rb
module AssosHelper
  def image_svg(asso)
    case asso.category
    when "animaux"
      image_tag('animaux.svg', class: "svg_img")
    when "art"
      image_tag('art.svg', class: "svg_img")
    when "politique"
      image_tag('politique.svg', class: "svg_img")
    when "alimentation"
      image_tag('alimentation.svg', class: "svg_img")
    when "culture"
      image_tag('culture.svg', class: "svg_img")
    when "education"
      image_tag('education.svg', class: "svg_img")
    when "environnement"
      image_tag('environnement.svg', class: "svg_img")
    when "santé"
      image_tag('sante.svg', class: "svg_img")
    when "social"
      image_tag('social.svg', class: "svg_img")
    when "sport"
      image_tag('sport.svg', class: "svg_img")
    else
      image_tag('default_image.svg', class: "svg_img")
    end
  end
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/assos/_info_window.html.erb
<div class="infowindow">
  <h><%= link_to asso.name.capitalize, asso_path(asso)  %></h2>
  <p><%= asso.address %></p>
</div>

app/views/assos/index.html.erb
<div class="main-container">
  <div class="col-6">
    <div class="mapbox">
      <div class="map_style map" id="map"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
        data-image-selected="<%= image_url('pin_selected.svg') %>"
        data-image-unselected="<%= image_url('pin_unselected.svg') %>">
      </div>
    </div>

  </div>
  <div class="col-6">
    <div class="container">
      <div class="form-group col-12">
        <%= form_tag assos_path, method: :get, class:"d-flex justify-content-between align-items-end" do %>
            <%= text_field_tag :query,
              params[:query],
              class: "form-control asso",
              placeholder: " Trouver une asso 🔎"
            %>
            <%= submit_tag "Rechercher", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
    <div class="cards side-container">
      <% @assos.each do |asso| %>
        <div class="card asso-card" data-asso-id="<%= asso.id %>">
          <%= link_to asso_path(asso) do%>
            <h1><%=asso.name.capitalize.truncate(50) %></h1>
            <p> <strong>Total de mission :</strong> <%= asso.total_mission %></p>
            <p><%= asso.description.capitalize.truncate(150) %></p>
            <%= image_svg(asso) %>
            <h2><%= asso.city %></h2>

          <% end %>
        </div>
      <% end %>
     </div>
  </div>
</div>

app/views/assos/show.html.erb
<div class="flexasso">
  <div class="asso-container col-6">
    <div>
      <h1><%= @asso.name.capitalize %></h1>
      <h2><%= @asso.address.upcase %> , <%= @asso.zipcode%> - <%= @asso.city.upcase%></h2>
    </div>
    <div>
      <p><%= @asso.description %></p>
    </div>
    <div class="call-to-action">
      <button class="btn btn-success"> contacter </button>
      <%= image_svg(@asso) %>
    </div>
  </div>
  <div class="col-6">
    <div id="map"
      style="width: 100%; height: 200px;"
      data-markers="<%= @marker.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
      data-image-selected="<%= image_url('pin_selected.svg') %>"
      data-image-unselected="<%= image_url('pin_unselected.svg') %>">
    </div>

  </div>
</div>
<div class="container fav">
  <div class="card-favorite">
    <h2 class="asso-title">Missions mises en ligne par <%= @asso.name.capitalize %></h2>
    <% if @missions_around_me.to_a.empty? %>
      <p> Il semblerait que cette association n'ai pas publié de mission pour le moment ! 🕵️</p>

    <% else %>
      <div class="missions-cards">
        <% @missions_around_me.each do |mission| %>

            <div  class="card mission-card">
              <%= link_to mission_path(mission) do %>
                <div class="mission_card" id="mission-<%= mission.id %>">

                  <h1><%= mission.title%></h1>
                  <h5><%= mission.lieu %></h5>
                  <h4><%= mission.asso.name.capitalize %></h4>
                  <p><%= mission.type_mission %></p>
                  <% if user_signed_in? %>
                  <%= render "missions/toggle_favorite", mission: mission, user: current_user, from: 'asso_show' %>
                  <% end %>

                </div>
              <% end %>
            </div>

        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/favorites/index.html.erb
<div class="container fav">
  <div class="card-favorite">
      <div class="niveau">
        <div class="titre w-100">
        <h1 class="text-muted"> Mon tableau de bord</h1>
         <div class="badges d-flex flex-column justify-content-center align-items-center">
          <h4>Bravo ! Tu as ajouté ton premier favoris !  </h4>
            <%=image_tag('firstgreen.svg', class: "svg_img gros") %>
        </div>

        </div>
        <div class="text">
          <h4>Niveau 1/5 </h3>
          <p class="text-muted">Réalise ta première mission pour passer à l'étape suivante ! </p>
        </div>
          <div class="jauge">
            <div class="skills progress">10%</div>
          </div>



        <div class="  flexbox justify-content-between">
            <%=image_tag('firstgreen.svg', class: "svg_img") %>
            <%=image_tag('2.svg', class: "svg_img") %>
            <%=image_tag('5.svg', class: "svg_img") %>
            <%=image_tag('10.svg', class: "svg_img") %>
            <%=image_tag('15.svg', class: "svg_img") %>
        </div>

      </div>

      <div class="missions-cards">
        <% current_user.favorites_missions.each do |mission| %>
          <div  class="card mission-card">
            <div class="mission_card" id="mission-<%= mission.id %>">
                <% if user_signed_in? %>
                <%= render "missions/toggle_favorite", mission: mission, user: current_user, from: 'user_favorites' %>
                <% end %>
              <h1><%= mission.title%></h1>
              <h5><%= mission.lieu %></h5>
              <h4><%= mission.asso.name.capitalize %></h4>
              <p><%= mission.type_mission %></p>
              <%# <h4><%= mission.dispo %>
              </div>
              <div class="d-flex justify-content-between">
                <a href="mailto:habitathumanismelyon@gmail.com?subject=%20Participation%20à%20la%20mission%20N°1982&" target="_blank" class="btn btn-success">Contacter l'Asso</a>
                <a href="#" target="_blank" class="btn btn-primary">Mission réalisée</a>
                </div>
              </div>
             <% end %>
      </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Impactasso</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application' %>
    <%= favicon_link_tag %>

    <meta property="og:title" content="Impactasso" />
    <meta property="og:description" content="La solution pour trouver facilement des associations et des missions de bénévolat qui te ressemblent, autour de chez toi!" />
    <meta property="og:image" content="http://www.impactasso.xyz/logo.jpg" />
    <meta property="og:type" content="siteweb" />
    <meta property="og:url" content="http://www.impactasso.xyz" />
    <meta property="fb:app_id" content="59740542" />
    <meta property="og:image:width" content="1200" />
    <meta property="og:image:height" content="630" />


    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

    <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <div class="flex-grow">
      <%= yield %>
    </div>
     <%= render 'shared/footer' %>

  </body>

</html>

app/views/layouts/special.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Impactasso</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application' %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

      <%= yield %>

  </body>
      <%= render 'shared/footer' %>

</html>

app/views/missions/_info_window.html.erb
<div class="infowindow">
  <h2><%= link_to asso.name.capitalize, asso_path(asso)  %></h2>
  <p><%= asso.description.capitalize.truncate(20) %></p>
</div>

app/views/missions/_toggle_favorite.html.erb
<% if mission.in_favorite?(user) %>
  <%= link_to toggle_favorite_mission_favorites_path(mission, query: params[:query], from: from), class: "btn btn-ghost like float-right" do %>
    <div class="svg_img">
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
        <path fill-rule="evenodd" d="M3.172 5.172a4 4 0 015.656 0L10 6.343l1.172-1.171a4 4 0 115.656 5.656L10 17.657l-6.828-6.829a4 4 0 010-5.656z" clip-rule="evenodd" />
      </svg>
    </div>
  <% end %>
<% else %>
  <%= link_to toggle_favorite_mission_favorites_path(mission, query: params[:query], from: from), class: "btn btn-ghost like" do %>
    <div class="svg_img">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" />
      </svg>
    </div>
  <% end %>
<% end %>

app/views/missions/index.html.erb
<div class="form-group col-12">
  <h1>Rechercher une mission</h1>
      <%= form_tag missions_path, method: :get do %>
          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Trouver une mission 🔎"
          %>
          <%= submit_tag "Rechercher", class: "btn btn-primary " %>
      <% end %>
  </div>
<div class="main-container">
  <div class="col-6">
   <div class="cards side-container" id="mission-cards">
    <% @missions.each do |mission| %>
      <div class="card mission-card" id="mission-<%= mission.id%>">
       <%= content_tag "div style=display:none; id=mission#{mission.id}-data", mission.asso.to_json%>
          <%= link_to mission_path(mission) do%>
              <h1><%= mission.title%></h1>
            <%# <h2><%= mission.asso.name.capitalize%</h2> %>
              <p><%= mission.type_mission %></p>
              <h4><%= mission.dispo %><h4>
              <h5><%= mission.lieu %></h5>
            <% if user_signed_in? %>
              <%= render "missions/toggle_favorite", mission: mission, user: current_user, from: 'missions_index' %>
            <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>
  <div  class="col-6">
    <div class="displayasso">
      <div class="assoimgbg">
        <%= image_tag "9814.jpg", class: "img_preview", id:'placeholder' %>
        </div>
    </div>
  </div>
</div>

app/views/missions/show.html.erb
<div class="container">
<div class="main-container">
<div class="show-card col-12 col-lg-12">
      <h2><%= @mission.title %></h2>
      <li class="li-none"> <strong>Lieu :</strong> <%= @mission.lieu %></li>
      <li class="li-none"> <strong>Disponibilitée demandée :</strong> <%= @mission.dispo %></li>
      <li class="li-none"> <strong>Type de mission :</strong> <%= @mission.type_mission %></li>
      <li class="li-none"> <strong>date de mission :</strong> <%= @mission.date_mission %></li>
      <div class="d-flex justify-content-between align-items-center">
      <% if current_user %>
	     <%= render "missions/toggle_favorite", mission: @mission, user: current_user, from: 'mission_show' %>
          <a href="mailto:asso@orange.fr?subject=%20Participation%20à%20la%20mission%20N°1982&" target="_blank" class="btn-blue">Contacter l'Asso</a>
      <% end %>
</div>
</div>
</div>

app/views/offers/show.html.erb
<% content_for :meta_title, "#{@offer.name} is on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @offer.description %>
<% content_for :meta_image, cl_image_path(@offer.photo.path) %>

app/views/pages/_info_window.html.erb
<div class="infowindow">
  <h2><%= link_to asso.name.capitalize, asso_path(asso)  %></h2>
  <p><%= asso.description.capitalize.truncate(20) %></p>
</div>

app/views/pages/home.html.erb
<div class="main-container">
  <div class="home_banner">
    <div class="row">
      <div class="col-lg-6">
      <h1>Impact'Asso</h1>
      <h4>Agis facilement pour des causes qui te tiennent à coeur !</h4>

        <div class="form-group search-card">
            <%= form_tag search_path, method: :get do %>
              <div class="group">
            <h5>Je recherche : </h5>
                <input class="selector" type="radio" name="kind" value="assos" id="asso" checked="">
                <label for="asso">Associations</label>
                <input class="selector" type="radio" name="kind" value="missions" id="mission">
                <label for="mission">Missions</label>
              </div>
            <div class="group">
              <div class="form-group input-text d-flex">
                  <h5>Dans le domaine de : </h5>
                  <select class="form-control" name="category" id="category-select">
                    <option value="">Catégories</option>
                    <option value="Sport">Sport</option>
                    <option value="Social">Social</option>
                    <option value="Culture">Culture</option>
                    <option value="Santé">Santé</option>
                    <option value="Animaux">Animaux</option>
                    <option value="Art">Art</option>
                    <option value="Environement">Environement</option>
                    <option value="Politique">Politique</option>
                    <option value="Education">Education</option>
                    <option value="Alimentaire">Alimentaire</option>
                    </select>
                  </div>
              </div>
              <div class="group">
                <div class="form-group input-text d-flex">
                  <h5>À : </h5>
                  <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Ville" %>
                </div>
                <%= submit_tag "Rechercher", class: "btn btn-primary ", id: "btn-home", data: { disable_with: false }   %>
                <% end %>
              </div>
            </div>
          </div>
          <div class="col-lg-6">
            <%= image_tag "5278.jpg", class: "img_index" %>
            <h3>La solution pour trouver facilement des Associations et des missions de bénévolat autour de chez toi! </h3>
          </div>
        </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer flexbox">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
    <a href="#"><i class="fab fa-youtube-square"></i></i></a>
  </div>
  <div class="footer-list flexbox justify-content-center">
    <ul>
      <li><a href="#">Nous contacter</a></li>
      <li><a href="#">On parle de nous</a></li>
      <li><a href="#">Notre histoire</a></li>
    </ul>
  </div>
</div>

app/views/users/_form.html.erb
<%= simple_form_for(piece) do |f| %>
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :email %>
    <%= f.input :adres %>
    <%= f.input :city %>
    <%= f.input :postal_code %>
    <%= f.input :phone_numbe %>
    <%= f.submit %>
    <% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="edit-form">
    <%= render "form", user: @user %>
  </div>
</div>

app/views/users/index.html.erb
<ul>
  <% @users.each do |user| %>
    <li><%= user.first_name %></li>
    <li><%= user.last_name %></li>
    <li><%= user.email %></li>
    <li><%= user.address %></li>
    <li><%= user.city %></li>
    <li><%= user.postal_code %></li>
    <li><%= user.phone_number %></li>
  <% end %>
</ul>

app/views/users/new.html.erb
<div class="container">
    <div class="new-form">
        <h1> Nouveau utilisateur</h1>
      <%= render "form", user: @user %>
    </div>
  </div>

app/views/users/show.html.erb
<div class="container max-height-100vh">
  <div class="card-profil">
    <div class="profil-image">
      <img src="https://ca.slack-edge.com/T02NE0241-U01KJ5YC57U-b66fe5f15aaf-512" style="height: 200px; border-radius: 32px" alt="Margaux Gaudriot" />
    </div>
      <h1> <strong>Margaux Gaudriot</strong></h1>
     <div class="card-profil-info">
      <p><em><i class="fas fa-envelope-square"></i> <%= @user.email %> </em></p>
      <p><em><i class="fas fa-map-marker-alt"></i> 21 rue des capucins 69001 Lyon</em></p>
      <p><em><i class="fas fa-phone-alt"></i> 06 84 03 05 83</em></p>
    </div>
    <div class="card-profil-description">
      <h1><strong> Biographie</strong></h1>
      <p> Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam, facilis atque! Eius tempora labore inventore fugit dolores, maiores perspiciatis ipsum voluptatibus, eaque, cum nostrum nobis, porro. Eum odio laudantium neque?
      Lorem ipsum dolor, sit amet consectetur adipisicing elit. Officia, earum! Quaerat, perferendis qui itaque a vitae. Architecto unde dignissimos natus distinctio iusto molestias doloribus magnam ut temporibus perspiciatis. Dicta, magnam.
      </p>
    </div>
  </div>
</div>